### ISSUE TITLE
Errors in Style File is Mute

### ISSUE THREAD

**Issue by JscLee** [Real-Rocket-Panda/fprime-visual#116]
The error in style file is not aware by the user. The graph is generated using the default style.

![2](https://user-images.githubusercontent.com/8522904/43050234-3653ae68-8dd3-11e8-8d16-d77f3543a79e.gif)

**Comment by SteveZhangBit** [comment]
Add try-catch block at cymanager update json, when the style file is not a valid cytoscape style config.

**Comment by SteveZhangBit** [comment]
Add error-handling when the style file is not a valid css file.
