### ISSUE TITLE
Build button doesn't refresh the graph

### ISSUE THREAD

**Issue by JscLee** [Real-Rocket-Panda/fprime-visual#117]
Delete SG1 and all its connections in fpp file. Then click build button to compile. The graph is not refreshed after rebuilt, and the user needs to click refresh manually.
![3](https://user-images.githubusercontent.com/8522904/43050306-ad983632-8dd4-11e8-8cd6-d9736c68da06.gif)

**Comment by SteveZhangBit** [comment]
Refresh the current view after refresh
