### ISSUE TITLE
Default style update doesn't properly apply

### ISSUE THREAD

**Issue by JscLee** [Real-Rocket-Panda/fprime-visual#120]
After updating the default style, the views still renders with the old default style, and has to be refreshed to be applied with the new default style.

![4](https://user-images.githubusercontent.com/8522904/43051436-d12b094a-8de7-11e8-9f58-d46bdf899598.gif)

**Comment by SteveZhangBit** [comment]
@JscLee provide the system test script

**Comment by SteveZhangBit** [comment]
Refresh should update the style for those cached views, but does not change their positions.

**Comment by SteveZhangBit** [comment]
Show a dialog when closing an unsaved view. Stringify and compare the cytoscape json
