### ISSUE TITLE
Errors when attempting to run with `npm run build`

### ISSUE THREAD

**Issue by ljreder** [Real-Rocket-Panda/fprime-visual#137]
It seems the tool runs ok using MAC OSX 10.3 and the *.dmg file supplied but when I attempt to use npm version 6.4 to run it this is what happens:

[LMC-051300:Workspace/isf-dev/fprime-visual] reder% npm install

> fsevents@1.2.4 install /Users/reder/Documents/Workspace/isf-dev/fprime-visual/node_modules/fsevents
> node install

[fsevents] Success: "/Users/reder/Documents/Workspace/isf-dev/fprime-visual/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> electron-chromedriver@1.8.0 install /Users/reder/Documents/Workspace/isf-dev/fprime-visual/node_modules/electron-chromedriver
> node ./download-chromedriver.js

successfully dowloaded and extracted!

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/reder/Documents/Workspace/isf-dev/fprime-visual/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> electron@2.0.7 postinstall /Users/reder/Documents/Workspace/isf-dev/fprime-visual/node_modules/electron
> node install.js

npm WARN fprime-visual@0.1.3 No repository field.
npm WARN fprime-visual@0.1.3 No license field.

added 1882 packages from 2086 contributors and audited 17630 packages in 29.684s
found 3 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
[LMC-051300:Workspace/isf-dev/fprime-visual] reder% npm run build

> fprime-visual@0.1.3 build /Users/reder/Documents/Workspace/isf-dev/fprime-visual
> node .electron-vue/build.js && electron-builder

 ___              __                        __                       ___       __    
/\_ \       __   /\ \__     ____           /\ \       __  __   __   /\_ \     /\ \   
\//\ \    / ,.`\ \ \ ,_\   / ,__\  _______ \ \ \____ /\ \/\ \ /\_\  \//\ \    \_\ \  
  \_\ \_ /\  __/  \ \ \/  /\__, `\/\______\ \ \  ,. \\ \ \_\ \\/\ \   \_\ \_ /\ ,. \ 
  /\____\\ \____\  \ \ \_ \/\____/\/______/  \ \____/ \ \____/ \ \ \  /\____\\ \____\
  \/____/ \/____/   \ \__\ \/___/             \/___/   \/___/   \/_/  \/____/ \/___ /
                     \/__/                                                           

  / building main process
  / building renderer process

   ERROR  failed to build main process

    Hash: fa27404f73057d411225
    Version: webpack 3.12.0
    Time: 2689ms
      Asset     Size  Chunks  Chunk Names
    main.js  1.05 kB       0  main
       [0] ./src/main/index.ts 1.55 kB {0} [built]
       [1] external "electron" 42 bytes {0} [not cacheable]
       [2] external "path" 42 bytes {0} [not cacheable]
    
    ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyUtil.ts
    [tsl] ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyUtil.ts(36,57)
          TS2339: Property 'id' does not exist on type 'NodeCollection'.
    
    ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyUtil.ts
    [tsl] ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyUtil.ts(46,39)
          TS2339: Property 'id' does not exist on type 'NodeCollection'.
    
    ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyManager.ts
    [tsl] ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyManager.ts(234,47)
          TS2694: Namespace 'cytoscape' has no exported member 'ElementStylesheet'.
    
    ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyManager.ts
    [tsl] ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyManager.ts(396,43)
          TS2345: Argument of type 'NodeCollection' is not assignable to parameter of type 'NodeSingular'.
      Property 'cy' is missing in type 'NodeCollection'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fprime-visual@0.1.3 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fprime-visual@0.1.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/reder/.npm/_logs/2018-08-15T22_46_33_477Z-debug.log

The attached is the log file referenced.  Here are some useful versions of things:

[LMC-051300:Workspace/isf-dev/fprime-visual] reder% npm -v
6.4.0
[LMC-051300:Workspace/isf-dev/fprime-visual] reder% node -v
v8.11.3

[2018-08-15T22_46_33_477Z-debug.log](https://github.com/Real-Rocket-Panda/fprime-visual/files/2291949/2018-08-15T22_46_33_477Z-debug.log)

**Comment by ljreder** [comment]
Oh yes when I try and run it with `npm run dev` this is what happens as well:

[LMC-051300:Workspace/isf-dev/fprime-visual] reder% npm run dev

> fprime-visual@0.1.3 dev /Users/reder/Documents/Workspace/isf-dev/fprime-visual
> node .electron-vue/dev-runner.js

         ___                      __                                                                
   __   /\_ \       __     ___   /\ \__    _ __    ___     ___              __  __  __  __     __   
 / ,.`\ \//\ \    / ,.`\  /'___\ \ \ ,_\  /\` __\ / __`\ /' _ `\   _______ /\ \/\ \/\ \/\ \  / ,.`\ 
/\  __/   \_\ \_ /\  __/ /\ \__/  \ \ \/  \ \ \/ /\ \_\ \/\ \/\ \ /\______\\ \ \/ |\ \ \_\ \/\  __/ 
\ \____\  /\____\\ \____\\ \____\  \ \ \_  \ \_\ \ \____/\ \_\ \_\\/______/ \ \___/ \ \____/\ \____\
 \/____/  \/____/ \/____/ \/____/   \ \__\  \/_/  \/___/  \/_/\/_/           \/__/   \/___/  \/____/
                                     \/__/                                                          
  getting ready...

┏ Main Process ---------------

  compiling...

┗ ----------------------------

┏ Main Process ---------------

  Hash: d81e956ece2fbf0882b3
  Version: webpack 3.12.0
  Time: 19699ms
    Asset    Size  Chunks  Chunk Names
  main.js  189 kB       0  main
     [0] external "path" 42 bytes {0} [not cacheable]
     [1] external "fs" 42 bytes {0} [not cacheable]
     [2] external "electron" 42 bytes {0} [not cacheable]
     [8] ./node_modules/electron-debug 160 bytes {0} [built]
    [14] ./node_modules/electron-devtools-installer/dist/utils.js 1.93 kB {0} [built]
    [15] ./src/main/index.ts 1.55 kB {0} [built]
    [16] multi ./src/main/index.dev.ts ./src/main/index.ts 40 bytes {0} [built]
    [17] ./src/main/index.dev.ts 830 bytes {0} [built]
    [18] ./node_modules/electron-debug/index.js 2.52 kB {0} [built]
    [19] ./node_modules/electron-localshortcut/index.js 8.36 kB {0} [built]
    [29] ./node_modules/electron-is-dev/index.js 256 bytes {0} [built]
    [30] ./node_modules/electron-devtools-installer/dist/index.js 5.14 kB {0} [built]
    [31] ./node_modules/semver/semver.js 36.5 kB {0} [built]
    [32] ./node_modules/electron-devtools-installer/dist/downloadChromeExtension.js 2.31 kB {0} [built]
    [47] external "https" 42 bytes {0} [not cacheable]
      + 33 hidden modules
  
  WARNING in ./node_modules/electron-debug/index.js
  81:45-58 Critical dependency: the request of a dependency is an expression
   @ ./node_modules/electron-debug/index.js
   @ ./src/main/index.dev.ts
   @ multi ./src/main/index.dev.ts ./src/main/index.ts
  
  WARNING in ./node_modules/electron-debug/index.js
  84:85-106 Critical dependency: the request of a dependency is an expression
   @ ./node_modules/electron-debug/index.js
   @ ./src/main/index.dev.ts
   @ multi ./src/main/index.dev.ts ./src/main/index.ts
  
  ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyUtil.ts
  [tsl] ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyUtil.ts(36,57)
        TS2339: Property 'id' does not exist on type 'NodeCollection'.
  
  ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyUtil.ts
  [tsl] ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyUtil.ts(46,39)
        TS2339: Property 'id' does not exist on type 'NodeCollection'.
  
  ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyManager.ts
  [tsl] ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyManager.ts(234,47)
        TS2694: Namespace 'cytoscape' has no exported member 'ElementStylesheet'.
  
  ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyManager.ts
  [tsl] ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyManager.ts(396,43)
        TS2345: Argument of type 'NodeCollection' is not assignable to parameter of type 'NodeSingular'.
    Property 'cy' is missing in type 'NodeCollection'.

┗ ----------------------------

┏ Renderer Process -----------

  Hash: 1f589802991bfff134d7
  Version: webpack 3.12.0
  Time: 21458ms
        Asset     Size  Chunks  Chunk Names
  renderer.js  3.74 MB       0  renderer
   styles.css   265 kB       0  renderer
     [0] ./node_modules/vue/dist/vue.esm.js 292 kB {0} [built]
     [1] ./node_modules/vue-hot-reload-api/dist/index.js 6.24 kB {0} [built]
     [4] ./node_modules/vue-loader/lib/component-normalizer.js 2.9 kB {0} [built]
    [20] ./node_modules/ts-loader!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/renderer/App.vue 7.32 kB {0} [built]
    [31] multi ./.electron-vue/dev-client ./src/renderer/main.ts 40 bytes {0} [built]
    [32] ./.electron-vue/dev-client.js 731 bytes {0} [built]
    [33] (webpack)-hot-middleware/client.js?noInfo=true&reload=true 7.77 kB {0} [built]
    [44] ./src/renderer/main.ts 666 bytes {0} [built]
    [45] external "vue-tree-navigation" 42 bytes {0} [not cacheable]
    [46] ./node_modules/vuetify/dist/vuetify.js 835 kB {0} [built]
    [47] ./node_modules/vuetify/dist/vuetify.css 41 bytes {0} [built]
    [48] external "sprintf-js" 42 bytes {0} [not cacheable]
    [49] ./src/renderer/App.vue 1.83 kB {0} [built]
    [95] ./src/renderer/router/index.ts 564 bytes {0} [built]
   [100] external "vue-electron" 42 bytes {0} [not cacheable]
      + 89 hidden modules
  
  ERROR in ./src/renderer/store/CyUtil.ts
  [tsl] ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyUtil.ts(36,57)
        TS2339: Property 'id' does not exist on type 'NodeCollection'.
  
  ERROR in ./src/renderer/store/CyUtil.ts
  [tsl] ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyUtil.ts(46,39)
        TS2339: Property 'id' does not exist on type 'NodeCollection'.
  
  ERROR in ./src/renderer/store/CyManager.ts
  [tsl] ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyManager.ts(234,47)
        TS2694: Namespace 'cytoscape' has no exported member 'ElementStylesheet'.
  
  ERROR in ./src/renderer/store/CyManager.ts
  [tsl] ERROR in /Users/reder/Documents/Workspace/isf-dev/fprime-visual/src/renderer/store/CyManager.ts(396,43)
        TS2345: Argument of type 'NodeCollection' is not assignable to parameter of type 'NodeSingular'.
    Property 'cy' is missing in type 'NodeCollection'.
  Child html-webpack-plugin for "index.html":
           Asset     Size  Chunks  Chunk Names
      index.html  1.45 MB       0  
         [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 1.3 kB {0} [built]
         [1] ./node_modules/html-webpack-plugin/node_modules/lodash/lodash.js 540 kB {0} [built]
         [2] (webpack)/buildin/module.js 517 bytes {0} [built]
  Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/vuetify/dist/vuetify.css:
         [0] ./node_modules/css-loader!./node_modules/vuetify/dist/vuetify.css 276 kB {0} [built]
         [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]

┗ ----------------------------

┏ Electron -------------------

  Debugger listening on ws://127.0.0.1:5858/ecb1e211-d995-47c7-ae24-547dbd4ea146
  For help see https://nodejs.org/en/docs/inspector
  
┗ ----------------------------

**Comment by miaoever** [comment]
Hi Leonard @ljreder,

We investigated your logs and found the issue is caused by the backward compatibility of the @type/cytoscape package we depended on. 

We used the ver 3.2.1 of this package originally which worked fine before. Recently it upgraded to a new version which has the compatibility issue.

To fix the issue, we have fixed the version to 3.2.1 in the `package.json` file to ensure the right dependency version. We have pushed the new fix to the master branch.

For now, you can `git pull` to get the latest code from the master branch and delete the original `node_moduels` folder (which contains all the external dependencies) and run the `npm install` again to install the dependencies.

**Comment by ljreder** [comment]
Very nice it seems to build and run ok now.   The tests do not seem to work though:

[isf-dev] [LMC-051300:Workspace/isf-dev/fprime-visual] reder% npm test

> fprime-visual@0.1.3 test /Users/reder/Documents/Workspace/isf-dev/fprime-visual
> npm run fprime-test && npm run ui-test && npm run e2e

npm ERR! missing script: fprime-test

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/reder/.npm/_logs/2018-08-16T18_33_36_895Z-debug.log
npm ERR! Test failed.  See above for more details.
